name: Deploy

on:
  push:

jobs:
  build-and-deploy-package:
    name: "Build and Deploy Package"
    runs-on: ubuntu-latest
    
    steps:

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine Version
        id: version
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Build Release Package
        shell: bash
        run: |
          mkdir -p package
          dotnet nuget add source --username jbasinger --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ env.GITHUB_REPOSITORY_OWNER }}/index.json"
          dotnet pack --configuration Release -p:VERSION=${{ steps.gitversion.outputs.semVer }} -o packages
          dotnet nuget push "SVL.Process.${{ github.ref_name }}.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"