name: Deploy

on:
  push:
    branches-ignore:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-deploy-package:
    name: "Build and Deploy Package"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Release Package
        if: ${{ github.ref_type }} == 'tag'
        shell: bash
        run: |
          mkdir -p package
          dotnet nuget add source --username jbasinger --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ env.GITHUB_REPOSITORY_OWNER }}/index.json"
          dotnet pack --configuration Release -p:VERSION=${{ github.ref_name }} -o packages
          if [ -f "SVL.Process.${{ github.ref_name }}.nupkg" ]; then
            dotnet nuget push "SVL.Process.${{ github.ref_name }}.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
          else
            git push --delete origin ${{ github.ref_name }}
            echo "Solution version does not match tag. Package not pushed and tag deleted."
            return 1
          fi

      - name: Build Pre-Release Package
        if: ${{ github.ref_type }} == 'branch'
        shell: bash
        run: |
          dotnet nuget add source --username jbasinger --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ env.GITHUB_REPOSITORY_OWNER }}/index.json"
          dotnet pack --configuration Release --version-suffix ${{ github.ref_name }} -o packages
          dotnet nuget push packages --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"